<?php
/* First-run content: what the static site showed. Replace it from the admin panel. */

const SEED_SETTINGS = [
    'email' => 'hello@dakpionimc.com',
    'phone' => '+880 1XXX-XXXXXX',
    'whatsapp' => '',
    'address' => 'House 12, Road 5, Dhanmondi, Dhaka 1209, Bangladesh',
    'address_short' => 'Dhanmondi, Dhaka',
    'map_url' => '',
    'hours' => 'Saturday – Thursday, 10:00 AM – 7:00 PM',
    'response_time' => 'Within one business day',
    'facebook' => '', 'instagram' => '', 'linkedin' => '', 'youtube' => '', 'tiktok' => '',
    'site_name' => 'Dakpion IMC',
    'legal_name' => 'Dakpion IMC',
    'tagline' => 'Cultivating Ideas, Crafting Success.',
    'careers_link' => '',
    'notify_email' => '',
    'budgets' => "Under ৳1 lakh\n৳1–3 lakh\n৳3–10 lakh\n৳10 lakh+\nNot sure yet",
    'success_title' => 'Message received!',
    'success_text' => 'A strategist from our team will contact you within one business day.',
    'og_image' => '', 'ga_id' => '', 'pixel_id' => '', 'gsc_verify' => '',
    'show_notes' => '1',
];

const SEED_COLLECTIONS = [
    'stats' => [
        ['value' => '9', 'suffix' => '+', 'label' => 'Years building brands in Bangladesh'],
        ['value' => '120', 'suffix' => '+', 'label' => 'Integrated campaigns launched'],
        ['value' => '60', 'suffix' => '+', 'label' => 'Brands across 8 industries'],
        ['value' => '92', 'suffix' => '%', 'label' => 'Clients who stay year after year'],
    ],
    'services' => [
        ['name' => 'Strategy & Research', 'slug' => 'strategy', 'icon' => 'target',
         'short' => 'Insight, positioning and a full-funnel plan before a single taka is spent.', 'tags' => 'Research, Positioning, Media plan',
         'lead' => 'Every great campaign starts with a sharp insight. We study your market, customers and competitors, then build a positioning and full-funnel plan that tells every channel what to do.',
         'points' => "Market & consumer research\nCompetitor & category audit\nBrand positioning & messaging\nAudience personas & journeys\nIntegrated media planning\nKPI & budget frameworks",
         'kpi1' => 'Clarity', 'kpi1_label' => 'One plan for every channel', 'kpi2' => 'Focus', 'kpi2_label' => 'Budget on what works', 'cta' => 'Discuss strategy'],
        ['name' => 'Branding & Creative', 'slug' => 'branding', 'icon' => 'brand',
         'short' => 'Identities and big ideas that make your brand impossible to ignore.', 'tags' => 'Identity, Packaging, Campaigns',
         'lead' => 'From naming and logos to packaging and campaign concepts — identities and ideas that look premium, feel consistent and work across every touchpoint.',
         'points' => "Logo & visual identity\nBrand guidelines & tone of voice\nPackaging & label design\nCampaign concepts & key visuals\nCopywriting in Bangla & English\nPrint, POSM & collateral",
         'kpi1' => 'Distinct', 'kpi1_label' => 'Stand out on every shelf & feed', 'kpi2' => 'Consistent', 'kpi2_label' => 'One look, everywhere', 'cta' => 'Discuss branding'],
        ['name' => 'Digital & Social Media', 'slug' => 'digital', 'icon' => 'social',
         'short' => 'Always-on content, community and creators across every platform.', 'tags' => 'Content, Community, Influencers',
         'lead' => 'We plan, create and manage your social presence every day — content calendars, reels, community replies and influencer collaborations that keep your brand in the conversation.',
         'points' => "Social strategy & calendars\nReels, motion & static content\nCommunity & inbox management\nInfluencer & KOL programs\nSocial listening & reputation\nMonthly analytics reports",
         'kpi1' => 'Daily', 'kpi1_label' => 'Facebook, Instagram & TikTok', 'kpi2' => 'Weekly', 'kpi2_label' => 'YouTube & LinkedIn', 'cta' => 'Discuss digital'],
        ['name' => 'Performance & SEO', 'slug' => 'performance', 'icon' => 'ads',
         'short' => 'Meta, Google and TikTok ads plus SEO — optimised daily for sales.', 'tags' => 'Meta Ads, Google Ads, SEO',
         'lead' => 'Data-driven campaigns on Meta, Google, YouTube and TikTok, plus SEO that compounds over time. We optimise against the numbers that matter — leads, sales and cost per acquisition.',
         'points' => "Meta, Google & TikTok ads\nLead generation funnels\nSearch engine optimisation\nLanding pages & CRO\nPixel, GA4 & conversion tracking\nRemarketing & retention",
         'kpi1' => '3.4x', 'kpi1_label' => 'Average ROAS*', 'kpi2' => '−38%', 'kpi2_label' => 'Cost per lead*', 'cta' => 'Discuss performance'],
        ['name' => 'Video & Production', 'slug' => 'production', 'icon' => 'video',
         'short' => 'TVC, OVC, reels, 3D and CGI — produced in-house, script to screen.', 'tags' => 'TVC, Reels, 3D & CGI',
         'lead' => 'Our in-house production team handles concept, script, shoot and post — from 15-second reels to full TVCs, product photography, 3D animation and architectural CGI.',
         'points' => "TVC & OVC production\nReels & short-form video\nCorporate & brand films\nProduct & lifestyle photography\n3D animation & CGI\nMotion graphics & explainers",
         'kpi1' => 'In-house', 'kpi1_label' => 'Script → shoot → edit', 'kpi2' => 'Every format', 'kpi2_label' => '16:9 · 9:16 · 1:1', 'cta' => 'Discuss video'],
        ['name' => 'Web & MarTech', 'slug' => 'tech', 'icon' => 'web',
         'short' => 'Websites, e-commerce, CRM and automation built to convert.', 'tags' => 'Websites, E-commerce, CRM',
         'lead' => 'Fast, mobile-first websites, landing pages and online stores — connected to the CRM, automation and analytics you need to turn traffic into revenue.',
         'points' => "Corporate & brand websites\nE-commerce stores\nLanding pages & microsites\nCRM & lead management\nEmail, SMS & WhatsApp automation\nDashboards & reporting",
         'kpi1' => '< 2s', 'kpi1_label' => 'Page load target', 'kpi2' => '100%', 'kpi2_label' => 'Mobile-first builds', 'cta' => 'Discuss web'],
        ['name' => 'ATL Media & PR', 'slug' => 'atl', 'icon' => 'tv',
         'short' => 'TV, radio, print, billboards and press — mass reach, measured.', 'tags' => 'TV & Radio, OOH, PR',
         'lead' => 'We plan and buy TV, radio, newspaper and outdoor media at the right rates, and run press relations that give your brand authority and earned coverage.',
         'points' => "TV & radio planning and buying\nNewspaper & magazine ads\nBillboards & OOH\nPress releases & media relations\nCrisis & reputation management\nPost-campaign reach reports",
         'kpi1' => 'National', 'kpi1_label' => 'TV & radio reach', 'kpi2' => 'City-wide', 'kpi2_label' => 'OOH networks', 'cta' => 'Discuss ATL media'],
        ['name' => 'BTL & Activation', 'slug' => 'btl', 'icon' => 'flag',
         'short' => 'Launches, events, sampling and retail — brands people can touch.', 'tags' => 'Events, Sampling, Retail',
         'lead' => 'Launch events, road shows, sampling, in-store branding and trade programs — executed on the ground with trained teams and reported with real-time data.',
         'points' => "Product launches & events\nSampling & road shows\nRetail & in-store branding\nTrade & channel programs\nExhibitions & stalls\nCorporate events & conferences",
         'kpi1' => 'Nationwide', 'kpi1_label' => 'Activation teams', 'kpi2' => 'Real-time', 'kpi2_label' => 'Field reporting', 'cta' => 'Discuss BTL'],
    ],
    'projects' => [
        ['title' => 'Beverage brand national launch', 'industry' => 'FMCG', 'kind' => '360° Launch', 'summary' => 'TVC, OOH, social and 400+ retail activations rolled out as one campaign.', 'kpi' => '+212%', 'kpi_label' => 'Retail sell-through in 3 months', 'tags' => 'TVC, OOH, BTL, Social', 'cats' => 'integrated,activation', 'theme' => '1', 'featured' => '1'],
        ['title' => 'Multi-specialty hospital growth', 'industry' => 'Healthcare', 'kind' => 'Digital + Performance', 'summary' => 'New website, doctor branding and always-on Meta & Google campaigns.', 'kpi' => '4.1x', 'kpi_label' => 'More appointment leads', 'tags' => 'Web, Ads, SEO', 'cats' => 'digital,performance', 'theme' => '2', 'featured' => '1'],
        ['title' => 'Premium residential launch', 'industry' => 'Real Estate', 'kind' => 'Brand + Leads', 'summary' => 'Brand identity, 3D walkthrough film and a lead-gen funnel with CRM.', 'kpi' => '−46%', 'kpi_label' => 'Cost per qualified lead', 'tags' => 'Branding, CGI, CRM', 'cats' => 'branding,production', 'theme' => '3', 'featured' => '1'],
        ['title' => 'Fashion D2C scale-up', 'industry' => 'E-commerce', 'kind' => 'Performance', 'summary' => 'Creative testing system and retention flows that tripled monthly revenue.', 'kpi' => '5.2x', 'kpi_label' => 'Return on ad spend', 'tags' => 'Meta Ads, TikTok, CRO', 'cats' => 'performance,digital', 'theme' => '4', 'featured' => '1'],
        ['title' => 'University admission season', 'industry' => 'Education', 'kind' => 'Admissions', 'summary' => 'Open-day events, student reels and a counselling CRM across 6 cities.', 'kpi' => '3,800+', 'kpi_label' => 'Admission enquiries', 'tags' => 'Events, Reels, CRM', 'cats' => 'integrated,activation', 'theme' => '5', 'featured' => '1'],
        ['title' => 'Group identity refresh', 'industry' => 'Corporate', 'kind' => 'Rebrand', 'summary' => 'New identity system, guidelines and annual report for a diversified group.', 'kpi' => '12→1', 'kpi_label' => 'Companies, one brand', 'tags' => 'Identity, Guidelines, Print', 'cats' => 'branding', 'theme' => '6', 'featured' => ''],
        ['title' => 'Diagnostic centre film', 'industry' => 'Healthcare', 'kind' => 'Brand Film', 'summary' => 'Cinematic facility film with CGI equipment sequences for TV and digital.', 'kpi' => '2.3M', 'kpi_label' => 'Brand film views', 'tags' => 'Film, CGI, OVC', 'cats' => 'production', 'theme' => '2', 'featured' => ''],
        ['title' => 'Nationwide snack road show', 'industry' => 'FMCG', 'kind' => 'Sampling', 'summary' => 'Trained teams across 18 districts with real-time dashboard reporting.', 'kpi' => '120K', 'kpi_label' => 'Samples distributed', 'tags' => 'Road show, Sampling', 'cats' => 'activation', 'theme' => '1', 'featured' => ''],
    ],
    'team' => [
        ['role' => 'Founder & CEO', 'dept' => 'Leadership', 'initials' => 'CEO', 'home' => '1'],
        ['role' => 'Head of Strategy', 'dept' => 'Strategy & Planning', 'initials' => 'STR', 'home' => '1'],
        ['role' => 'Creative Director', 'dept' => 'Creative & Design', 'initials' => 'CD', 'home' => '1'],
        ['role' => 'Head of Digital', 'dept' => 'Social & Content', 'initials' => 'DIG', 'home' => '1'],
        ['role' => 'Performance Lead', 'dept' => 'Ads, SEO & Analytics', 'initials' => 'ROI', 'home' => ''],
        ['role' => 'Head of Production', 'dept' => 'Video, 3D & CGI', 'initials' => 'PRD', 'home' => ''],
        ['role' => 'Media & Activation Lead', 'dept' => 'ATL, BTL & PR', 'initials' => 'ACT', 'home' => ''],
    ],
    'testimonials' => [
        ['quote' => 'We used to juggle four agencies. Dakpion replaced all of them with one plan and one report — and our launch hit its targets a month early.', 'name' => 'Client name', 'role' => 'Head of Marketing, FMCG brand', 'initials' => 'MK'],
        ['quote' => 'They understood healthcare audiences from day one. Patient enquiries grew every single month after the campaign went live.', 'name' => 'Client name', 'role' => 'Director, Multi-specialty hospital', 'initials' => 'DR'],
        ['quote' => 'From the 3D film to the billboards and the Facebook funnel, everything felt like one brand. Our sales team noticed the lead quality immediately.', 'name' => 'Client name', 'role' => 'CEO, Real estate developer', 'initials' => 'SA'],
        ['quote' => 'The creative testing system changed our business. We finally know which ads make money — and we scale them with confidence.', 'name' => 'Client name', 'role' => 'Founder, D2C fashion label', 'initials' => 'NH'],
        ['quote' => 'Open days were packed and our counsellors had a CRM full of warm leads. Best admission season we have had.', 'name' => 'Client name', 'role' => 'Registrar, Private university', 'initials' => 'TR'],
    ],
    'clients' => [],
    'packages' => [
        ['name' => 'Digital Growth', 'summary' => 'An always-on digital presence that performs.', 'price' => 'Monthly retainer', 'features' => "Social media management\nMonthly content & reels\nMeta & Google ads\nMonthly performance report", 'button' => 'Get a quote', 'highlight' => '', 'badge' => ''],
        ['name' => '360° Brand Partner', 'summary' => 'Your full marketing department — strategy to activation.', 'price' => 'Annual partnership', 'features' => "Dedicated strategy & account team\nBranding, creative & production\nDigital, performance & SEO\nATL media buying & PR\nBTL activations & events\nQuarterly business reviews", 'button' => 'Book discovery call', 'highlight' => '1', 'badge' => 'Most popular'],
        ['name' => 'Campaign Launch', 'summary' => 'For a launch, rebrand or seasonal push.', 'price' => 'Project based', 'features' => "Campaign strategy & big idea\nKey visual & TVC / OVC\nIntegrated media plan\nLaunch event or activation", 'button' => 'Plan a launch', 'highlight' => '', 'badge' => ''],
    ],
    'industries' => [
        ['name' => 'Healthcare', 'slug' => 'healthcare', 'icon' => 'health', 'text' => 'Where Dakpion began. Ethical, trust-first marketing for hospitals, clinics, diagnostics and doctors — booking websites, doctor branding, facility films and appointment campaigns.', 'tags' => 'Doctor branding, Booking websites, Facility films, Lead campaigns'],
        ['name' => 'FMCG & Retail', 'slug' => 'fmcg', 'icon' => 'bag', 'text' => 'Launch and grow consumer brands with mass-reach creative, shelf-winning packaging and trade programs that move stock.', 'tags' => 'Launches, Packaging, TVC & OOH, Sampling'],
        ['name' => 'Real Estate', 'slug' => 'realestate', 'icon' => 'building', 'text' => 'Premium project branding, 3D walkthroughs and lead funnels that deliver qualified buyers — tracked from first click to booking.', 'tags' => 'Project branding, 3D & CGI, Lead funnels, CRM'],
        ['name' => 'E-commerce & D2C', 'slug' => 'ecommerce', 'icon' => 'cart', 'text' => 'Performance-first growth: conversion-optimised stores, creative testing at scale and retention flows that bring buyers back.', 'tags' => 'Meta & TikTok, CRO, Creative testing, Retention'],
        ['name' => 'Education', 'slug' => 'education', 'icon' => 'edu', 'text' => 'Admission campaigns that fill seats — institutional branding, open days, student content and counselling CRM.', 'tags' => 'Admissions, Open days, Student reels, CRM'],
        ['name' => 'Corporate & B2B', 'slug' => 'corporate', 'icon' => 'briefcase', 'text' => 'Reputation with the people who matter — identity, annual reports, PR, LinkedIn leadership and conferences.', 'tags' => 'Identity, PR, LinkedIn, Events'],
        ['name' => 'Food & Hospitality', 'slug' => 'hospitality', 'icon' => 'food', 'text' => 'Craveable content, launch buzz and local reach that fill tables and rooms — with food photography and creator visits.', 'tags' => 'Food shoots, Launches, Influencers, Local SEO'],
        ['name' => 'Fashion & Lifestyle', 'slug' => 'fashion', 'icon' => 'brand', 'text' => 'Content-first brand building — seasonal lookbooks, reels, creator partnerships and pop-ups that turn followers into buyers.', 'tags' => 'Lookbooks, Creators, Pop-ups, E-com ads'],
    ],
    'faqs' => [
        ['question' => 'What does “360° marketing” actually mean?', 'answer' => 'Every channel your customer meets — social, search, TV, radio, billboards, shelves, events and your website — is planned and run as one connected campaign, with one message and one set of goals.'],
        ['question' => 'Can I hire you for just one service?', 'answer' => 'Yes. Many clients start with one service — like social media or a website — and expand as they see results. Everything we build plugs into a wider 360° plan later.'],
        ['question' => 'How do you measure results?', 'answer' => 'We agree KPIs up front — reach, leads, sales, cost per acquisition, brand lift — set up tracking across channels, and share a clear monthly report with next-step recommendations.'],
        ['question' => 'What budgets do you work with?', 'answer' => 'Growing SMEs and large enterprises alike. We recommend the channel mix that makes the most of your budget — digital-first or a full ATL + BTL rollout.'],
        ['question' => 'How quickly can a campaign go live?', 'answer' => 'Digital campaigns can launch in 2–3 weeks. Integrated campaigns with production, TVC or on-ground activation usually take 5–8 weeks from brief to launch.'],
    ],
    'process' => [
        ['title' => 'Discover', 'text' => 'We audit your brand, market, competitors and current marketing — and find where the real growth is hiding.', 'tags' => 'Brand audit, Market research, Week 1'],
        ['title' => 'Strategise', 'text' => 'Positioning, audiences, the big idea and a channel-by-channel plan with KPIs and budget.', 'tags' => 'Big idea, Media plan, Week 2'],
        ['title' => 'Create', 'text' => 'Design, copy, video, web and media assets — produced in-house so everything looks and sounds like one brand.', 'tags' => 'Production, Week 3–5'],
        ['title' => 'Launch', 'text' => 'Go live across digital, ATL and BTL in one coordinated rollout, with tracking from day one.', 'tags' => 'Rollout, Week 6'],
        ['title' => 'Optimise', 'text' => 'Weekly optimisation, monthly reports and quarterly reviews — we scale what works and cut what doesn’t.', 'tags' => 'Reporting, Ongoing'],
    ],
    'values' => [
        ['icon' => 'target', 'title' => 'Results over noise', 'text' => 'Every idea ties to a business goal and a number we can report on.'],
        ['icon' => 'layers', 'title' => 'Integrated by design', 'text' => 'Strategy, creative, digital and media in one team — no hand-off gaps.'],
        ['icon' => 'users', 'title' => 'Partners, not vendors', 'text' => 'An extension of your team, with honest advice and full transparency.'],
        ['icon' => 'bolt', 'title' => 'Local soul, global craft', 'text' => 'Rooted in Bangladeshi culture, built to international standards.'],
    ],
    'timeline' => [
        ['year' => '2016', 'text' => 'Founded in Dhaka as a creative and digital studio.'],
        ['year' => '2019', 'text' => 'Became a trusted marketing partner for doctors, clinics and hospitals.'],
        ['year' => '2022', 'text' => 'Added in-house video, 3D / CGI production and performance marketing.'],
        ['year' => 'Today', 'text' => 'A full 360° IMC agency — strategy, creative, digital, ATL, BTL and PR.'],
    ],
];
